# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

runtime: python37
service: default

# Handlers define how to route requests to your application.
handlers:
- url: /api/v1/(.*)
  script: auto
  secure: always

- url: /tasks/(.*)
  script: auto
  secure: always

- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /favicon\.png
  static_files: build/favicon.png
  upload: build/favicon\.png

# unused for now
# - url: /service-worker\.js
#   static_files: build/service-worker.js
#   upload: build/service-worker\.js

- url: /manifest\.json
  static_files: build/manifest.json
  upload: build/manifest\.json

- url: /static/(.*)
  static_files: build/static/\1
  upload: build/static/(.*)

- url: .*
  static_files: build/index.html
  upload: build/index.html


